branch-defaults:
  main:
    environment: Uxplorer-production
environment-defaults:
  Uxplorer-production:
    branch: null
    repository: null
global:
  application_name: uxplorer
  default_ec2_keyname: null
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
